services:
  ros2:
    image: ${DOCKER_REGISTRY}/ros2_humble_full_desktop:${IMAGE_TAG}
    container_name: ros2_gui
    environment:
      - DISPLAY=${DISPLAY}                 # Pass host DISPLAY env
      - QT_X11_NO_MITSHM=1                 # Fix some Qt issues
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix      # Share X socket
    network_mode: "host"                   # Optional, for easier networking
    stdin_open: true
    tty: true
