services:
  ros2_turtle_sim_node:
    image: ${DOCKER_REGISTRY}/ros2_humble_full_desktop:${IMAGE_TAG}
    container_name: ros2_turtle_sim_gui
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    command: bash -c "source /opt/ros/humble/setup.bash && ros2 run turtlesim turtlesim_node"
    networks:
      - ros2_net
    stdin_open: true
    tty: true

  ros2_turtle_sim_node_comm:
    image: ${DOCKER_REGISTRY}/ros2_humble_full_desktop:${IMAGE_TAG}
    container_name: ros2_turtle_sim_comm
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    networks:
      - ros2_net
    stdin_open: true
    tty: true

networks:
  ros2_net:
    driver: bridge
